menu_planning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("menu_planning.planning.urls")),
]

menu_planning/planning/models.py
from django.db import models
from django.urls import reverse


# Model for Days of the Week
class Day(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menu', args=[str(self.id)])

    @classmethod
    def populate_days(cls):
        days_of_week = ['Понеделник', 'Вторник', 'Сряда', 'Четвъртък', 'Петък', 'Събота', 'Неделя']
        for day_name in days_of_week:
            cls.objects.get_or_create(name=day_name)


# Model for Meals (Breakfast, Lunch, Dinner)
class Meal(models.Model):
    day = models.ForeignKey(Day, on_delete=models.PROTECT, related_name='meals')
    name = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.name} on {self.day.name}"

    def get_absolute_url(self):
        return reverse('dishes', args=[str(self.id)])


# Model for Dishes
class Dish(models.Model):
    meal = models.ForeignKey('Meal', on_delete=models.CASCADE, related_name='dishes')
    description = models.TextField(blank=True, null=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name} for {self.meal.name}"

    def get_absolute_url(self):
        return reverse('category', args=[str(self.id)])


# Model for Products (Warehouse)
class Product(models.Model):
    name = models.CharField(max_length=100)
    unit = models.CharField(
        max_length=20,
        choices=[("броя", "броя"), ("гр.", "гр.")],
        default="гр.",
    )
    quantity_in_stock = models.DecimalField(max_digits=10, decimal_places=3, default=0)
    calories_per_100g = models.DecimalField(max_digits=5, decimal_places=1, null=True, blank=True)  # Optional field
    def __str__(self):
        return f"{self.name} ({self.unit} {self.quantity_in_stock})"


# Model for Recipes
class Recipe(models.Model):
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, related_name='recipes')
    name = models.CharField(max_length=100)
    description = models.TextField(blank=False, null=False)
    products = models.ManyToManyField(Product, through='RecipeProduct')

    def __str__(self):
        return f"Recipe for {self.dish.name}"


# Through Model for Recipe Products
class RecipeProduct(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity_required = models.DecimalField(max_digits=10, decimal_places=2)
    unit = models.CharField(
        max_length=20,
        choices=[("броя", "броя"), ("гр.", "гр.")],
        default="гр.",
    )

    @property
    def calories(self):
        if self.product.calories_per_100g and self.unit == 'гр.':
            return (self.quantity_required / 100) * self.product.calories_per_100g
        return 0  # If calories or unit isn't set properly

    def __str__(self):
        return f"{self.quantity_required} {self.unit} of {self.product.name} for {self.recipe.name}"


# Model for Shopping List
class ShoppingList(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Shopping List for {self.recipe.name}"


class ShoppingListItem(models.Model):
    shopping_list = models.ForeignKey(ShoppingList, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    unit = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.quantity} {self.unit} of {self.product.name}"


# Through Model for Shopping List Products
class ShoppingListProduct(models.Model):
    shopping_list = models.ForeignKey(ShoppingList, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity_available = models.DecimalField(max_digits=10, decimal_places=2)
    quantity_required = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.quantity_required} {self.product.unit} of {self.product.name} for {self.shopping_list.recipe.dish.meal.day.name}"

templates/add_dishes.html
{% extends 'navbar.html' %}
{% load static %}
{% block header %}

    <title>Ястия за {{ meal.name }}</title>

<h1>Ястия за {{ meal.name }}</h1>


<!-- Display the form for adding a new dish -->
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Запис</button>
</form>


<a href="{% url 'menu' meal.day.id %}">Назад към меню</a>

{% endblock header %}

templates/category.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
{#    <title>Категория за {{ dish.name }}</title>#}
{#</head>#}
{#<body>#}
{#    <h1>Категориия за  {{ dish.name }}</h1>#}
{##}
{#    <ul>#}
{#        {% for category in categories %}#}
{#            <li>#}
{#                <a href="{% url 'recipe_list' category.id %}">{{ category.name }}</a>#}
{#            </li>#}
{#        {% empty %}#}
{#            <li>Няма избрана категория за това ястие.</li>#}
{#        {% endfor %}#}
{#    </ul>#}
{##}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Добави категория</button>#}
{#    </form>#}
{##}
{#    <a href="{% url 'dishes' dish.meal.id %}">Назад към ястия</a>#}
{#</body>#}
{#</html>#}

templates/create_meal.html
{% extends 'navbar.html' %}
{% load static %}
{% block header %}
    <title>Създайте ново ястие</title>

<section id="index-headline">
    <div class="index-message">
        <div class="plant-card">
            <h1>Създайте ново ястие за <br><br>{{ day.name }}</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <br><button type="submit"><h1><span>Запис</span></h1></button>
            </form>


        </div>
        <br>
        <button>
            <h1>
                <a href="{% url 'menu' day.id %}">Назад</a>
            </h1>
        </button>
    </div>

</section>

{% endblock header %}

templates/dish_delete.html
{% extends "navbar.html" %}

{% block header %}
    <section id="index-headline">
        <div class="index-message">
            <div class="plant-card">
                <h2>Are you sure you want to delete {{ meal.name }}?</h2>
                <form method="POST" action="{% url 'delete_dish' pk=dish.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Yes</button>
                    <a href="{% url 'home' %}" class="btn btn-secondary">Cancel</a>
                </form>
            </div>
        </div>
    </section>
{% endblock header %}

templates/dish_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if form.instance.pk %}Edit{% else %}Add{% endif %} Dish</title>
</head>
<body>
    <h1>{% if form.instance.pk %}Редактирай{% else %}Добави{% endif %} Ястие</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Запис</button>
    </form>

    <a href="{% if form.instance.pk %}{% url 'dishes' form.instance.meal.id %}{% else %}{% url 'dishes' meal.id %}{% endif %}">Отказ</a>
</body>
</html>

templates/dishes.html
{% extends 'navbar.html' %}
{% load static %}
{% block header %}

    <title>Рецепта за {{ meal.name }}</title>

    <section id="index-headline">
        <div class="index-message">
            <div class="plant-card">
                <h6><span>Ястие за {{ meal.name }}</span></h6>
                <ol>
                    <h1>{% for dish in dishes %}
                        <li>
                            <a href="{% url 'recipe_list' pk=dish.id %}"><span>{{ dish.name }}</span></a>
                        </li>
                    {% empty %}
                        <li>Няма налични ястия.</li>
                    {% endfor %}</h1>
                </ol>

                <!-- Display the form for adding a new dish -->
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br>
                    <button type="submit"><h1><span>Добави ново ястие</span></h1></button>
                </form>
                {% for dish in dishes %}
                    <h1>
                        <button><a href="{% url 'delete_dish' dish.id %}"><span>Изтрий {{ dish.name }}</span></a></button>
                        {% empty %}</h1>
                {% endfor %}


            </div>
            <button>
                <h1>
                    <a href="{% url 'menu' meal.day.id %}"><span>Назад към меню</span></a>
                </h1>
            </button>
        </div>

    </section>
{% endblock header %}

templates/index.html
{% extends 'navbar.html' %}
{% load static %}
{% block header %}

<body>
<section id="index-headline">
{#    <div class="index-message">#}
<div class="plant-card">
        <ul class="blog">
            {% for day in days %}
                <div>
                    <a href="{{ day.get_absolute_url }}">
                        <img src="/static/images/fruits.jpg" alt="{{ day.name }}"/>
                    </a>
{#                    <p>Menu for {{ day.name }}</p>#}
                    <a href="{{ day.get_absolute_url }}"><span>Меню за {{ day.name }}</span></a>
                </div>
            {% endfor %}
        </ul>
{#    </div>#}
</div>

</section>
<div class="index-message">
<div id="index-headline">
<h1>
    <button><a href="{% url 'summary_shopping_list' %}">
        <span>Summary Shopping List</span>
    </a></button></h1>
</div>
</div>
</body>


{% endblock header %}

templates/login.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
{#    <script src="{% static 'js/head_tagscript.js' %}"></script>#}
    <meta charset="utf-8">
    <title>Login Form</title>
    <link rel="icon" type="image/x-icon" href="/static/images/favicon.ico">
    <link href="{% static '/css/login_style.css' %}" rel="stylesheet" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/popper.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
     <meta name="csrf-token" content="{{ csrf_token }}">
</head>
<body>
<div class="box">
    <h2>LOG IN</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="inputBox">
            <input autocomple="off" type="text" name="username" required="">
            <label>Username</label>
        </div>
        <div class="inputBox">
            <input type="password" name="password" required="">
            <label>Password</label>
        </div>
        <input type="submit" name="" value="log_in">
    </form>
    <div class="regist">
        <p>Don't have an account? <a href="{% url 'register' %}">Sign Up</a></p>
    </div>
</div>
{% for message in messages %}
    <p id="messages">{{ message }}</p>
{% endfor %}
</body>
</html>

templates/menu.html
{% extends 'navbar.html' %}
{% load static %}
{% block header %}
    <title>Меню за {{ day.name }}</title>
<section id="index-headline">
    <div class="index-message">
        <div class="plant-card">
            <h1>Меню за {{ day.name }}</h1><br>

                <h1>
                    <ol>
                         {% for meal in meals %}
                            <li><a href="{% url 'dishes' meal.id %}"><span>{{ meal.name }}</span></a></li>
                    {% empty %}
                        <span>Няма налични ястия за този ден.</span>
                    {% endfor %}
                    </ol>
                </h1>

            <br>
<button>
    <h1>
        <a href="{% url 'create_meal' day.id %}"><span>Добави меню</span></a>
    </h1>
</button>
            <br><br>
    {% for meal in meals %}
        <h1>
    <button><a href="{% url 'delete_meal' pk=meal.id %}"><span>Изтрий {{ meal.name }}</span></a></button>
        {% empty %}
        </h1>
{% endfor %}

        </div>
        <br>
        <button>
            <h1><a href="{% url 'home' %}"><span>Назад към календар</span></a></h1>
        </button>
        <br>
{#        <button>#}
{#            <h1>#}
{#                <a href="{% url 'delete_meal' pk=meal.id %}"> Изтрий</a>#}
{#            </h1>#}
{#        </button>#}


    </div>


</section>
{% endblock header %}

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token }}">

    <!-- Preconnect for external resources -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <!-- Use CDN for Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Minified and combined CSS -->
    <link href="{% static '/css/landing.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/style.css" %}"/>

    <title>Menu Planning</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
</head>
<body>
    <nav class="navbar navbar-expand-sm flex-row-reverse" id="navbar">
        {% if user.is_authenticated %}
            <ul class="navbar-nav px-3 flex-row-reverse">
                <li class="nav-item text-nowrap">
                    <a class="nav-link active" href="{% url 'logout' %}" id="log-out">
                        Sign out
                    </a>
                </li>
            </ul>
        {% else %}
            <ul class="navbar-nav">
                <li class="nav-item align-middle">
                    <a class="nav-link" href="{% url 'login' %}" id="log-in">
                        Log In
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}" id="sign-up">
                        Sign Up
                    </a>
                </li>
            </ul>
        {% endif %}
    </nav>

    <!-- Move scripts to the end -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" defer></script>
</body>
{% block header %}
{% endblock header %}
</html>

templates/recipe.html
{% extends 'navbar.html' %}
{% load static %}
{% block header %}
    <section id="index-headline">
        <div class="index-message">
            <div class="plant-card">
                <h1>Рецепта за <span>{{ dish.name }}</span></h1>
                <h5>
                    {% for recipe in recipes %}
                        <ol><em>{{ recipe.name }}-{{ recipe.description }}</em></ol><br>
                        <button>
                            <h1>
                                <a href="{% url 'recipe_detail' recipe.id %}"><span>Виж рецептата</span></a>
                            </h1>
                        </button>
                    {% empty %}
                        <li>Няма налични рецепти за това ястие.</li>
                    {% endfor %}
                </h5>
{#                {% for recipe in recipes %}#}
{#                    <button>#}
{#                        <h1>#}
{#                            <a href="{% url 'delete_recipe' recipe.id %}">Изтрии {{ recipe.name }}</a>#}
{#                        </h1>#}
{#                    </button>#}
{#                {% endfor %}#}


                <!-- Form to add a new recipe -->
                <h5><span>Създай нова рецепта</span></h5>
                <form method="post" action="{% url 'recipe_list' dish.id %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit"><h1><span>Добави рецепта</span></h1></button>
                </form>
            </div>
            <button>
                <h1>
                    <a href="{% url 'dishes' dish.meal.id %}"><span>Назад към ястия</span></a>
                </h1>
            </button>
        </div>
    </section>

{% endblock header %}

templates/register.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
{#    <script src="{% static 'js/head_tagscript.js' %}"></script>#}
    <meta charset="utf-8">
    <title>Registration Form</title>
    <link rel="icon" type="image/x-icon" href="/static/images/favicon.ico">
    <link href="{% static '/css/login_style.css' %}" rel="stylesheet" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <!-- <link rel="stylesheet" href="/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <!-- <script src="/static/js/bootstrap.min.js"></script> -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="box">
    <h2>SIGN UP</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="inputBox">
            {{ form.username }}
            <label>Username</label>
        </div>
        <div class="inputBox">
            {{ form.email }}
            <label>Email</label>
        </div>
        <div class="inputBox">
            {{ form.password1 }}
            <label>Password</label>
        </div>
        <div class="inputBox">
            {{ form.password2 }}
            <label>Password (Again)</label>
        </div>
        <input type="submit" name="" value="register">
    </form>
    <div class="login">
        <p>Already have account? <a href="{% url 'login' %}">Login</a></p>
    </div>
</div>
{{ form.errors }}
{#<script src="{% static 'js/body_tagscript.js' %}"></script>#}
</body>
</html>

templates/shopping_list.html
{% extends 'navbar.html' %}
{% load static %}
{% block header %}
    <title>Shopping List for {{ day.name }}</title>

   <section id="index-headline">
        <div class="index-message">
    <div class="plant-card">

    <h1>Shopping List за {{ day.name }}</h1>
        <br>
    {% if shopping_lists %}
        {% for shopping_list in shopping_lists %}
            <h1>Рецепта за: {{ shopping_list.recipe.name }}</h1>
            <br>
            <h1><ol>
                {% for product in shopping_list.recipe.recipeproduct_set.all %}
                    <li>
                       <span>{{ product.product.name }}-{{ product.quantity_required }} {{ product.unit }}</span>
                    </li><br>
                {% endfor %}
            </ol>
            </h1>
        {% endfor %}
    {% else %}
        <p>No shopping list available for this day.</p>
    {% endif %}
</div>
            <button>
                <h1>
                <a href="{% url 'menu' day.id %}"><span>Назад към меню</span></a>
            </h1>
            </button>
</div>

</section>

{% endblock header %}

templates/summary_shopping_list.html
{% extends 'navbar.html' %}
{% load static %}
{% block header %}
    <title>Summary Shopping List</title>

    <section id="index-headline">
        <div class="index-message">
            <div class="plant-card">
                <h2>Summary Shopping List</h2>

                {% if summary %}
                    <ul>
                        {% for item in summary %}
                            <h1>
                                <oli>
                                    <span>{{ item.product__name }} - {{ item.total_quantity }} {{ item.product__unit }}</span>
                                </oli>
                            </h1>
                        {% endfor %}
                    </ul>
                {% else %}
                    <br>
                    <h4>Няма продукти за пазаруване.</h4>
                {% endif %}


            </div>
            <br>
            <button>
                <h1>
                    <a href="{% url 'home' %}"><span>Назад към календар</span></a>
                </h1>
            </button>
        </div>

    </section>

{% endblock header %}